### ISSUE TITLE
Supporting Openiddict?

### ISSUE THREAD

**Issue by Snuffsis** [thecloudnativewebapp/OidcProxy.Net#117]
It does support identity server. So I assume it also does support openiddict, is this the case?

I have been trying to make it work with an auth server running openiddict and auth code with pkce flow and such. But when ut redirects back tl exchange code, it just redirects back to the login again, and thus trigger the authorize endpoint once more and then fails.

**Comment by appie2go** [comment]
Hi there,

Thanks for your feedback. Can you describe the steps to reproduce?

Thanks in advance,

**Comment by Snuffsis** [comment]
I will try to provide what I can.

So first, I start my AuthServer running OpenIdDict and it has an authorized application with redirecturi (https://localhost:44449/account/login/callback ) and all the required scopes, offline_access and so on and using auth code with pkcd flow,  and postlogoutredirecturi ("https://localhost:44449/" ) set up.

In the SPA we have a button that calls account/login of the above baseurl and it works. It redirects to the auth server with its login page. And i can login and get all the details.
But the redirect from the SPA is requesting to redirect back to /account/login, which means it will redirect back to the login page and try to do reauthorize. Which gives me this error:
![image](https://github.com/thecloudnativewebapp/OidcProxy.Net/assets/8822958/9b47ad2b-2f6b-417a-9c2e-74856b388381)


For the full flow from the logs its this:
```
OpenIddict.Server.OpenIddictServerDispatcher: Information: The request URI matched a server endpoint: Authorization.
OpenIddict.Server.OpenIddictServerDispatcher: Information: The authorization request was successfully extracted: {
  "response_type": "code",
  "state": "hJxZM6jsjcClUgLzh9miQQ",
  "code_challenge": "B7fFBkp4i5WBgWsDbbSFIJmZPY-SzDAimt7DNSOMPXw",
  "code_challenge_method": "S256",
  "client_id": "customerPortalClient",
  "redirect_uri": "https://localhost:44449/account/login/callback",
  "scope": "openid profile offline_access api1"
}.
OpenIddict.Server.OpenIddictServerDispatcher: Information: The authorization request was successfully validated.```

After this output i get to the login page.
And then the logs output the same message again, indicating again that it hits the login endpoint once more for the authserver, instead of the exchange endpoint.
Here is the logoutput from the authserver at this point:
```
OpenIddict.Server.OpenIddictServerDispatcher: Information: The authorization response was successfully returned to 'https://localhost:44449/account/login/callback' using the query response mode: {
  "code": "[redacted]",
  "state": "hJxZM6jsjcClUgLzh9miQQ",
  "iss": "https://localhost:44323/"
}.
OpenIddict.Server.OpenIddictServerDispatcher: Information: The request URI matched a server endpoint: Token.
OpenIddict.Server.OpenIddictServerDispatcher: Information: The token request was successfully extracted: {
  "code": "[redacted]",
  "scope": "openid profile offline_access api1",
  "redirect_uri": "https://localhost:44449/account/login/callback",
  "code_verifier": "I20Hy6RH86jA7jJkTqHjv14qlAHROUDwh7msmtbNUJ8",
  "grant_type": "authorization_code",
  "client_id": "customerPortalClient",
  "client_secret": "[redacted]"
}.
OpenIddict.Server.OpenIddictServerDispatcher: Information: The token request was rejected because the 'scope' parameter was not allowed.
OpenIddict.Server.OpenIddictServerDispatcher: Information: The response was successfully returned as a JSON document: {
  "error": "invalid_request",
  "error_description": "The 'scope' parameter is not valid in this context.",
  "error_uri": "https://documentation.openiddict.com/errors/ID2074"
}.
```

Let me know if there is anything else you need.

**Comment by Snuffsis** [comment]
I just managed to get it working.

The issue was on my side. I was running an outdated version of the library that made use of the /account thing. I updated it so it now uses /.auth/* endpoints and it works fine.

The only limitation now is that it doesn't seem to support encrypted Json Web Tokens.

**Comment by appie2go** [comment]
Hi,

Great that you've managed to get it working. 

Let's close this issue, and let's create a new issue for the encrypted token issue? Again, please provide some direction on how to reproduce the issue. Then i can see if this is something we want to support and can manage to implement.

Cheers,
