### ISSUE TITLE
Huge delay when calling /.auth/login with autorization server on the web

### ISSUE THREAD

**Issue by rvdleij** [thecloudnativewebapp/OidcProxy.Net#118]
Situation: I implemented an autorization server with OpenIdDict which I try to use from my local OidcProxy.Net installation.

When the OidcProxy.Net installation + autorization server are running on localhost it works fine: navigation to /.auth/login is handled quickly.
But when the autorization server runs on the web (on some domain I own) and the OidcProxy.NET still runs locally, the call to /.auth/login takes about 20 seconds and then finally succeeds. So: in the end it works, but for some reason there is a huge delay and I cannot find out what this delay actually causes.

**Comment by appie2go** [comment]
Hi there,

The /.auth/login endpoint does two things:

- It queries the /.well-known/openid-configuration (discovery) endpoint of the identity-provider
- It redirects the user to the authorize-endpoint specified in that discovery endpoint

The behaviour you describe typically occurs when one of those endpoints is responding slowly. Can you rule that out?

Thanks in advance!

**Comment by rvdleij** [comment]
Thx for your quick response!

I think I can rule out both things:

- When I enter the address of the discovery endpoint manually in the browser I immediately get a response
- When I copy the generated URL for redirection to the autorize endpoint and enter this manually in the browser and submit, I also get a quick response

**Comment by appie2go** [comment]
Check,

And when you run the OidcProxy on the same computer, pointing to the same identity provider, the component is still responsive? I'm asking this because that we can make sure it has to do with the web-environment.

Also, have you enabled logging? The module has quite extensive logging, you should be able to see exactly what happens.

**Comment by rvdleij** [comment]
Ok, you mean: run the OidcProxy on the same server as where the identity provider runs, right? If yes: I did not test that combination yet, so I will do that.

**Comment by appie2go** [comment]
Yes, please do!

**Comment by rvdleij** [comment]
I just tested this combination: the OidcProxy application and the authorization server application are hosted (in IIS) on the same server. And now the OidcProxy application responds quickly when I navigate to the /.auth/login endpoint.

**Comment by appie2go** [comment]
Great! It seems to have been a network issue?

**Comment by rvdleij** [comment]
Well, my impression now is also that it must be something in the communication between OidcProxy, running on my local machine, to the autorization server on the web server. But still not clear what the delay causes.
You mentioned: "have you enabled logging?" Can you briefly explain what / where to do for that? Then I can look into the loggin on my local machine.

**Comment by appie2go** [comment]
The code uses the standard ASP.NET Core logging. (ILogger<T>)  When you configure a sync according to the spec, you should be able to see exactly what is happening, read more on how to enable it here: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-8.0

Cheers,

**Comment by rvdleij** [comment]
I dived into the logging and (in an attempt to pinpoint exactly where the delay occurs) I cloned the OidcProxy, referred to the source and started the step debugger. During the handling of /.auth/login, it appeared that this line took a very long time to get past this line in OpenIdConnectIdentityProvider ->

var request = await client.PrepareLoginAsync();

So yes, I guess this prooves that something is wrong with the connection to the server, but still not clear to me what it is :-)

**Comment by rvdleij** [comment]
I assume I should be able to find the root cause by configuring logging, so that I will not only see the log messages in the OidcProxy.Net application, but also in the IdentityModel.OidcClient packages, right? I'm not so experienced with that yet, so I'll go through the some tutorials first ;-) But all together I think this issue can be closed.

**Comment by appie2go** [comment]
Hi there,

That's correct. You should be able to see what's happening there. Chances are you'll see the problems occur when obtaining the discovery document or when creating the proof key. 

Maybe this is helpful to keep in mind: It wouldn't be the first time it turns out there's a firewall between the two services which offloads things and applies all sorts of policies causing a delay. 

Anyways, i'll close the issue for now, thanks very much for your feedback, and i would love to hear what turns out to be the issue. If you don't feel comfortable sharing it online, you can also share it via e-mail: oidcproxy.net@gmail.com

Cheers!

**Comment by rvdleij** [comment]
Your hint about the firewall prooved to be very helpfull :-)
For a test, I temporary disabled the firewall on the server and everything worked fine.
Then activated the firewall again of course and guess what.. it keeps working. No clue yet what the exact cause is now, but it almost feels like the firewall needed this restart. I'll keep an eye on it! Thx again for your very helpfull support!

**Comment by appie2go** [comment]
Most welcome!
